
# Register in https://coinmarketcap.com/api/ to get an API key.
coinmarketcap_api: "YOUR_COINMARKETCAP_API_KEY"

usd_upload_price: 0        # Price in USD per TB of bandwidth upload.
usd_download_price: 25     # Price in USD per TB of bandiwdth download.
usd_storage_price: 0.5     # Price in USD per TB of stored data.
collateral_ratio: 2        # Recommended collateral ratio between 1.5 and 2.